version: 2.1
jobs:
 build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

    steps:
      - checkout
      - run: npm install
      - run: npx tsc
      - run: npm test